- name: Allow kubeadm traffic
  ufw:
    rule: allow
    port: "{{ kubeadm_port }}"
    proto: tcp
  tags:
    - base
    - firewall
  notify: Enable ufw

- name: Add kubernetes (google) apt key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
    # notify: refresh apt cache
  tags:
    - kube_packages

- name: Configure kubernetes repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt/ kubernetes-xenial main
    state: present
  tags:
    - kube_packages

- name: Install kubernetes packages
  apt:
    state: present
    name: "{{ item }}"
  with_items: "{{ kubernetes_packages }}"
  tags:
    - kube_packages

- name: Add kubelet extra args to service
  # We're adding --fail-swap-on because we have swap
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertbefore: "^ExecStart=$"
    line: "Environment=\"KUBELET_EXTRA_ARGS=--fail-swap-on=false --node-ip={{hostvars[inventory_hostname].ansible_all_ipv4_addresses | ipaddr('192.168.0.0/16') | first}}\""

- name: Update kubelet cluster domain
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: "cluster-domain"
    line: "Environment=\"KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain={{ kubernetes_cluster_domain }}\""
    state: present

# Not sure this is needed because we do it again later
- name: Enable and start the kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - kube

- name: Ensure kernel modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter 
    - dm_snapshot # for glusterfs
    - dm_mirror   # for glusterfs
    - dm_thin_pool # for glusterfs

- name: Update kernel settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Get crictl
  command: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl creates=go/bin/crictl
