apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: huginn-web-ingress
spec:
  rules:
  - host: hugs.sharkbaitextraordinaire.com
    http:
      paths:
      - backend:
          serviceName: huginn-web
          servicePort: http
        path: /
status:
  loadBalancer: {}
