apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kanboard
  annotations:
    # Use traefik to serve this ingress
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: kanboard.sharkbaitextraordinaire.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kanboard
          servicePort: http
