apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  # Change the resturl parameter or your storage won't work
  # It is the IP of the heketi service's endpoint.
  # Alternatively, kube-dns should resolve this correctly
  #resturl: "http://heketi.default.svc.cluster.local:8080"
  resturl: "http://:8080"
