# Tasks to configure ipsec tunnels between nodes in the cluster
# Assume that pre-generated certificates and keys are present in ../files/
# so that we have files like this:
# - ca.crt.pem , the ca certificate
# - host1.crt.pem
# - host1.key.pem
# - host2.crt.pem
# - host2.key.pem
# - host3.crt.pem
# - host2.key.pem
# I've generated them via radiac's caman script because I use it for other stuff
# alternatively, just use a pre-shared key
- name: install ipsec tools
  apt:
    name: ipsec-tools
    state: present

- name: Deploy intermediate ca certificate to nodes
  copy:
    src: ../files/intermediate.ca.crt.pem
    dest: /etc/ipsec.d/cacerts/intermediate.ca.crt.pem

- name: Deploy root ca certificate to nodes
  copy:
    src: ../files/root.ca.crt.pem
    dest: /etc/ipsec.d/cacerts/root.ca.crt.pem

- name: Copy certificate to host
  copy:
    src: ../files/{{ inventory_hostname }}.crt.pem
    dest: /etc/ipsec.d/certs/{{ inventory_hostname }}.crt.pem

- name: Copy key to host
  copy:
    src: ../files/{{ inventory_hostname}}.key.pem
    dest: /etc/ipsec.d/private/{{ inventory_hostname }}.key.pem

- name: configure ipsec.conf
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf

- name: configure ipsec secrets
  template:
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets

- name: restart strongswan service
  service:
    name: strongswan
    state: restarted
