---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chompy-ingress
  annotations:
    # Use traefik to serve this ingress
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: chomp.xn--9q8h2cq1m.ws
    http:
      paths:
      - path: /
        backend:
          serviceName: chompy-grafana
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-ingress
  annotations:
    # Use traefik to serve this ingress
    kubernetes.io/ingress.class: "traefik"
    # Configure basic auth
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: chompy-basic-auth
spec:
  rules:
  - host: monitoring.xn--9q8h2cq1m.ws
    http:
      paths:
      - path: /prometheus
        backend:
          serviceName: orbiting-condor-prometheus-server
          servicePort: 80
      - path: /alertmanager
        backend:
          serviceName: orbiting-condor-prometheus-alertmanager
          servicePort: 80
