kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-cfg
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      # Redirect all http traffic to https
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
      # Add a dashboard and API endpoint
      [entryPoints.dashboard]
      # This port is used in the deployment
      address = ":8081"

    [api]
    entryPoint = "dashboard"
    dashboard = true
    [api.statistics]
    recentErrors = 10

    [metrics]
      [metrics.statistics]
      recentErrors = 50
      [metrics.prometheus]
      entryPoint = "dashboard"
      buckets = [0.1,0.3,1.2,5.0]
      
    [acme]
    email = "vigevenoj@gmail.com"
    # /etc/traefik/ is backed by a persistent volume (see the deployment spec)
    storage = "/etc/traefik/acme.json"
    acmeLogging = true
    onDemand = false
    onHostRule = true
    # staging server for test deployments
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"
    caServer = "https://acme-v01.api.letsencrypt.org/directory"
    entryPoint = "https"
      [acme.httpChallenge]
      entryPoint = "http"

    [[acme.domains]]
    main = "xn--9q8h2cq1m.ws"
    [[acme.domains]]
    main = "whatcolorischristinashair.com"
