# Configuration for Huginn workers.
# This does not configure the Huginn web interface. For that, see the hugin-web configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    io.kompose.service: huginn-threaded
  name: huginn-threaded
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: huginn-threaded
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: huginn-threaded
    spec:
      containers:
      - args:
        - /scripts/init
        - bin/threaded.rb
        env:
        - name: DATABASE_ADAPTER
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-adapter
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-name
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-password
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-username
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: database-port
        - name: DATABASE_ENCODING
          # This isn't secret
          value: utf8
        - name: POSTGRES_PORT_5432_TCP_PORT
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: postgres-port-tcp-port
        - name: POSTGRES_PORT_5432_TCP_ADDR
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: postgres-port-tcp-addr
        - name: APP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: huginn-configuration
              key: app-secret-token
        image: huginn/huginn-single-process
        imagePullPolicy: IfNotPresent
        name: huginn-threaded
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: huginn-threaded
  name: huginn-threaded
spec:
  # No ClusterIP; this service provides workers for Huginn
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    io.kompose.service: huginn-threaded
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
