# Tasks for configuring etcd members
- name: Install etcd package
  apt:
    state: present
    name: "{{ item }}"
  with_items: "{{ etcd_packages }}"
  tags:
    - packages
    - etcd
    - etcd_packages

- name: Allow etcd traffic
  ufw:
    rule: allow
    port: 2379:2380
    proto: tcp
  tags:
    - etcd
  notify: Enable ufw

# The `etcd_uri` fact is used in the etcd.service.j2 template
- name: Set etcd facts
  set_fact:
    etcd_uri: "{{ inventory_hostname }}=https://{{hostvars[inventory_hostname].ansible_all_ipv4_addresses | ipaddr('192.168.0.0/16') | first}}:2380"

- name: initial etcd configuration
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify:
    - restart etcd with config change
