# Playbook to configure persistent storage provider
# ansible-playbook -i inventory storage.yml --ask-become-pass -b

- hosts: kubenodes[0] # Our master, but we really need any one host
  gather_facts: true
  become: false
  vars_files:
    -  ./vars/external_vars.yml

  tasks:
    - name: Label all nodes as glusterfs nodes
      command: "kubectl label node {{ item }} storagenode=glusterfs"
      loop: "{{ groups['kubenodes'] }}"

    - name: Download heketi-cli package
      get_url:
        # https://github.com/heketi/heketi/releases/download/v6.0.0/heketi-client-v6.0.0.linux.amd64.tar.gz
        url: https://github.com/heketi/heketi/releases/download/v6.0.0/heketi-client-v6.0.0.linux.amd64.tar.gz
        dest: /tmp/heketi-client-v6.0.0.linux.amd64.tar.gz
      register: downloaded_heketi

    - name: Extract heketi
      when: downloaded_heketi|succeeded
      unarchive:
        copy: no
        src: /tmp/heketi-client-v6.0.0.linux.amd64.tar.gz
        dest: /tmp
      register: extracted_heketi

    - name: Move heketi cli to usr local bin
      become: true
      when: extracted_heketi|succeeded
      copy:
        remote_src: true
        src: /tmp/heketi-client/bin/heketi-cli
        dest: /usr/local/bin
        mode: 0755
      register: copied_heketi_cli

    - name: Clean up downloaded heketi
      when: downloaded_heketi|succeeded and extracted_heketi|succeeded and copied_heketi_cli|succeeded
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/heketi-client-v6.0.0.linux.amd64.tar.gz
        - /tmp/heketi-client

    - name: Check out gluster-kubernetes code for k8s deployment
      git:
        repo: https://github.com/gluster/gluster-kubernetes.git
        dest: /tmp/gluster-kubernetes

    - name: Copy topology to node
      copy:
        src: 'files/topology.json'
        remote_src: no
        dest: /tmp/gluster-kubernetes/deploy/topology.json

    - name: Run gk-deploy script
      command: ./gk-deploy -g -v -c kubectl -n default -l ~/gkdeploy.log topology.json
      args:
        chdir: /tmp/gluster-kubernetes/deploy

