---
# This playbook tears down and resets the heketi/glusterfs systems

- hosts: kubenodes[0] # We have some stuff we have to run on a node
  gather_facts: true
  # become: true
  # vars_files:
  # - ./vars/external_vars.yml

  tasks:
    - name: Run gk-deploy in abort mode
      command: ./gk-deploy --abort
      args:
        chdir: /tmp/gluster-kubernetes/deploy


- hosts: kubenodes
  gather_facts: true
  become: true

  tasks:
    - name: Wipe block volumes
      debug:
        msg: "Remove lvm volumes and reset /dev/sdc to an empty block device, run vgs and vgremove"
