# This is a persistent volume claim for our mysql cluster
# It will contain data for all of our databases
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mushy-mysql
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-heketi-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
