---
kind: ConfigMap
apiVersion: v1
metadata:
  name: owntracks2db-blank-config
  namespace: default
data:
  config.yaml: |
    # config.yaml
    mqtt:
      host: 
      port: 
      ssl: 
      ca: 
      username: 
      password:
    database:
      host: 
      port: 
      username: 
      password: 
      dbname: 
